# Travis (http://travis-ci.org/) is a continuous integration
# service for open source projects. This file configures
# Travis to install and run "tox" test runner, which is
# configured in tox.ini file.

sudo: false
language: python
install: pip install tox
script: tox
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-tests
    - python: 3.4
      env: TOXENV=py34-tests
    - python: 3.5
      env: TOXENV=py35-tests
    - python: 3.6
      env: TOXENV=py36-tests
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37-tests
    - python: pypy
      env: TOXENV=pypy-tests
    - python: 2.7
      env: TOXENV=py27-install
    - python: 3.4
      env: TOXENV=py34-install
    - python: 3.5
      env: TOXENV=py35-install
    - python: 3.6
      env: TOXENV=py36-install
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37-install
    - python: pypy
      env: TOXENV=pypy-install
    - python: 2.7
      env: TOXENV=docs
